name: Check Main Branch
description: "Status check to determine pull requests only come from the stage branch"

on:
    pull_request:
        types:
            - opened
        branches:
            - main

jobs:
    check-main-branch:
        runs-on: self-hosted
        if: ${{ !github.event.repository.is_template }}
        steps:
            - name: Main Branch Check
              shell: bash
              run: |
                if [[ "${{ github.head_ref }}" != "stage" ]]; then
                    echo "Error: Pull requests to main must come from the stage branch"
                    exit 1
                fi